---
name: "Image: Rebuild"
permissions:
  packages: write
on:
  push:
    branches:
      - main
      - dev
    paths:
      - "images/**"
      - "!images/**/metadata.json"
      - "!images/**/README.md"

jobs:
  get-changes:
    name: Collect changes
    runs-on: ubuntu-latest
    outputs:
      addedOrModifiedImages: ${{ steps.collect-changes.outputs.addedOrModifiedImages }}
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Collect changes
        id: collect-changes
        uses: ./.github/actions/collect-changes

  determine-images:
    name: Determine Images to Build
    runs-on: ubuntu-latest
    needs: ["get-changes"]
    outputs:
      matrix: ${{ steps.get-changed.outputs.changes }}
    if: ${{ needs.get-changes.outputs.addedOrModifiedImages }} != '[]'
    steps:
      - name: Install tools
        run: sudo apt-get install moreutils jo

      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0

      - name: Fetch modified images
        id: get-changed
        shell: bash
        run: |
          declare -a changes_array=()
          while read -r app
          do
            while read -r channel
            do
              change="$(jo app="$app" channel="$channel")"
              changes_array+=($change)
            done < <(jq -r '.channels[] | .name' "./images/$app/metadata.json")
          done < <(echo '${{ needs.get-changes.outputs.addedOrModifiedImages }}' | jq --raw-output -c '.[]')

          output="$(jo -a ${changes_array[*]})"
          echo "changes=${output}" >> $GITHUB_OUTPUT

  images-build:
    uses: ramblurr/ovos-docker-extra/.github/workflows/action-image-build.yaml@dev
    needs:
      - determine-images
    with:
      imagesToBuild: "${{ needs.determine-images.outputs.matrix }}"
      pushImages: "true"
    secrets: inherit
